language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby
  - rbx-2

gemfile:
  - gemfiles/active_record_30.gemfile
  - gemfiles/active_record_31.gemfile
  - gemfiles/active_record_32.gemfile
  - gemfiles/active_record_40.gemfile
  - gemfiles/active_record_41.gemfile
  - gemfiles/active_record_42.gemfile
  - gemfiles/active_record_edge.gemfile
  - gemfiles/data_mapper_12.gemfile
  - gemfiles/mongo_mapper.gemfile
  - gemfiles/mongoid_24.gemfile
  - gemfiles/mongoid_30.gemfile
  - gemfiles/mongoid_31.gemfile
  - gemfiles/mongoid_40.gemfile
  - gemfiles/sinatra_13.gemfile
  - gemfiles/sinatra_14.gemfile

sudo: false

services: mongodb

script: "bundle exec rake spec"

cache: bundler

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/active_record_40.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/active_record_41.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/active_record_edge.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/mongoid_30.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/mongoid_31.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/mongoid_40.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/active_record_edge.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/active_record_edge.gemfile
    - rvm: 2.1
      gemfile: gemfiles/active_record_edge.gemfile
    - rvm: 2.2
      gemfile: gemfiles/active_record_30.gemfile
    - rvm: 2.2
      gemfile: gemfiles/active_record_31.gemfile
    - rvm: 2.2
      gemfile: gemfiles/active_record_32.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/active_record_30.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/active_record_31.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/active_record_32.gemfile
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/active_record_edge.gemfile
  fast_finish: true
